### PR TITLE
Add key generation methods using elliptic-php

### PR DESCRIPTION
**Pull request by eko2one**
@swentel How can we add tests for this?
Do you think we need validation for type hex and bit length?

### CODE REVIEW

**Comment by swentel** [comment]
I see there are tests in https://github.com/simplito/elliptic-php/blob/master/tests/ECDHTest.php - so I think we're fine to be honest.

**Comment by eko2one** [comment]
Well, just added a test for getPublicKey.

**Comment by swentel** [comment]
Oh nice! I think that looks good. Unless you've got anything else, I'll merge in a couple of minutes.

**Comment by eko2one** [comment]
LFG

**Comment by swentel** [comment]
I assume that's a yes? Not familiar with that one :)

**Comment by swentel** [comment]
Alright, done, thanks!

**Pull request merged**
